# Generated by Django 3.1.7 on 2021-03-19 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('four_digit_pass', models.CharField(blank=True, max_length=256, null=True)),
                ('private_key', models.CharField(blank=True, max_length=256, null=True)),
                ('auth_image', models.ImageField(null=True, upload_to='static/auth_image/<django.db.models.fields.CharField>')),
                ('profile_pic', models.ImageField(null=True, upload_to='static/profilepic')),
            ],
        ),
        migrations.CreateModel(
            name='Encrypted_files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_file', models.FileField(null=True, upload_to='static/encrypted_files')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='storage_app.user_data')),
            ],
        ),
    ]
