# Generated by Django 3.1.7 on 2021-03-19 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='auth_image',
        ),
    ]
