# Generated by Django 3.1.7 on 2021-03-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0002_remove_user_data_auth_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='four_digit_pass',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='private_key',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='profile_pic',
            field=models.ImageField(upload_to='static/profilepic'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='username',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
